# docker-compose.yml

name: wayfinder-backend-devcontainer

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    restart: no
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
    user: root
    volumes:
      - ./postgresdata:/home/postgres/pgdata/data

  django:
    build:
      context: ../ # Path to the project's root folder so that the Dockerfile commands can access the project
      dockerfile: ./.devcontainer/Dockerfile # Path to the Dockerfile
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      # Mount the root folder that contains .git
      - ../../:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - timescaledb
